server:
  port: 8090
  servlet:
    context-path: /api

spring:
  application:
    name: peekaboo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.3:3306/peekaboo?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root

  messages:
    encoding: utf-8
    basename: i18n/messages

  redis:
    host: 192.168.0.3
    port: 6379
    password: root

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

vertify:
  code:
    timeout: 300

sms:
  code:
    timeout: 300

user:
  token:
    timeout: 1800

jwt:
  expiration: 6000000
  id: codingjc
  secret: codingjc

tencent:
  sms:
    account:
      secret-id:
      secret-key:
      sms-sdk-app-id:
      template-id:
      sign-name:

xxl:
  job:
    admin:
      addresses: http://192.169.0.105:8080/xxl-job-admin
    accessToken: default_token
    executor:
      ip:
      address:
      appname:
      port: 38801
      logpath: logs/xxl-job/first-study
      logretentiondays: 7

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
